from typing import Any, Dict

class BaseSkill:
    """
    Base class that all skills must inherit from.
    Skills act as tools that the LLM can call.
    """
    name: str = ""
    description: str = ""
    parameters: dict = {}

    def run(self, **kwargs: Any) -> Any:
        """
        Execute the skill with the given arguments.
        
        Args:
            **kwargs: Keyword arguments containing the tool parameters generated by the LLM.
            
        Returns:
            Any: The result of the skill execution.
        """
        raise NotImplementedError("Skills must implement the run method")
